// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var padContent;
    padContent = function() {
      var windowHeight;
      windowHeight = $(window).height();
      return $('.slide-content').each(function() {
        var contentHeight, targetHeight;
        contentHeight = $(this).height();
        targetHeight = (windowHeight - contentHeight) / 2;
        return $(this).css('padding-top', targetHeight);
      });
    };
    padContent();
    return $(window).resize(padContent);
  });

}).call(this);
